[app]
host = "localhost"
port = 2021
name = "my_treasure_doc"
runMode = "release" # dev-开发模式 release-生产模式

[mysql]
host = "127.0.0.1"
port = 3306
user = "root"
password = "root"
charset = "utf8mb4"
dbName = "my_treasure_doc"

[log]
directory = "log"
showInConsole = true
format = "console"   # [json | console]

[redis]
enable = false
host = "127.0.0.1"
port = 6379
user = ""
password = ""
dbId = 0
