package hot

import (
	"fastduck/treasure-doc/module/hot_top/conf"
	"fastduck/treasure-doc/module/hot_top/model"
)

var UrlConfMap map[model.Source]*conf.UrlConf = map[model.Source]*conf.UrlConf{
	model.SourceLol:      {},
	model.SourceITHome:   {},
	model.SourceZhihu:    {},
	model.SourceWeibo:    {},
	model.SourceBilibili: {},
	model.SourceBaidu:    {},
	model.SourceV2EX:     {},
	model.SourceGitHub:   {},
	model.SourceDouyin:   {},
	model.SourceKuaishou: {
		Disabled: true,
	},
	model.SourceToutiao:     {},
	model.SourceJuejin:      {},
	model.Source36Kr:        {},
	model.SourceCSDN:        {},
	model.SourceTieba:       {},
	model.SourceZhihuDaily:  {},
	model.SourceCoolapk:     {},
	model.SourceHupu:        {},
	model.SourceHuxiu:       {},
	model.SourceJianshu:     {},
	model.SourceSmzdm:       {},
	model.SourceSspai:       {},
	model.SourceNeteaseNews: {},
	model.SourceQQNews:      {},
	model.SourceAcfun:       {},
	model.Source51CTO:       {},
	model.Source52Pojie:     {},
	model.SourceDoubanGroup: {},
	model.SourceDgtle:       {},
	model.SourceDoubanMovie: {},
	model.SourceEarthquake: {
		Disabled: true,
	},
	model.SourceGameres:       {},
	model.SourceGeekpark:      {},
	model.SourceGenshin:       {},
	model.SourceGuokr:         {},
	model.SourceHackernews:    {},
	model.SourceHelloGitHub:   {},
	model.SourceHistory:       {},
	model.SourceHonkai:        {},
	model.SourceHostloc:       {},
	model.SourceIfanr:         {},
	model.SourceMiyoushe:      {},
	model.SourceNewsmth:       {},
	model.SourceNgabbs:        {},
	model.SourceNodeseek:      {},
	model.SourceNytimes:       {},
	model.SourceProducthunt:   {},
	model.SourceSinaNews:      {},
	model.SourceSina:          {},
	model.SourceStarrail:      {},
	model.SourceThepaper:      {},
	model.SourceWeatheralarm:  {},
	model.SourceWeread:        {},
	model.SourceYystv:         {},
	model.SourceIthomeXijiayi: {},
}
