// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrderGood = "order_goods"

// OrderGood mapped from table <order_goods>
type OrderGood struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GoodID    int32          `gorm:"column:good_id;not null" json:"good_id"`
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName OrderGood's table name
func (*OrderGood) TableName() string {
	return TableNameOrderGood
}
