// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrderDetail = "order_detail"

// OrderDetail mapped from table <order_detail>
type OrderDetail struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderID   int32          `gorm:"column:order_id;not null" json:"order_id"` // 订单id
	GoodID    int32          `gorm:"column:good_id;not null" json:"good_id"`
	SkuID     int32          `gorm:"column:sku_id;not null" json:"sku_id"`              // sku id
	Price     float64        `gorm:"column:price;not null;default:0.0000" json:"price"` // 单价
	Quantity  int32          `gorm:"column:quantity;not null" json:"quantity"`          // 数量
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName OrderDetail's table name
func (*OrderDetail) TableName() string {
	return TableNameOrderDetail
}
