// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Nickname      string         `gorm:"column:nickname;not null" json:"nickname"`                 // '昵称'
	Account       string         `gorm:"column:account;not null" json:"account"`                   // '账号'
	Email         string         `gorm:"column:email" json:"email"`                                // '邮箱'
	Password      string         `gorm:"column:password;not null" json:"password"`                 // '密码'
	UserType      int32          `gorm:"column:user_type;not null;default:1" json:"user_type"`     // '1-普通用户,2管理员,100超级管理员'
	UserStatus    int32          `gorm:"column:user_status;not null;default:1" json:"user_status"` // '1-可用,2-不可用,3-未激活'
	Mobile        string         `gorm:"column:mobile" json:"mobile"`                              // '手机号'
	Avatar        string         `gorm:"column:avatar" json:"avatar"`                              // '头像地址'
	Bio           string         `gorm:"column:bio" json:"bio"`                                    // '个人说明'
	Token         string         `gorm:"column:token" json:"token"`                                // '登陆token'
	TokenExpire   time.Time      `gorm:"column:token_expire" json:"token_expire"`                  // 'token超时时间'
	LastLoginIP   string         `gorm:"column:last_login_ip" json:"last_login_ip"`                // '最后登陆ip地址'
	LastLoginTime time.Time      `gorm:"column:last_login_time" json:"last_login_time"`            // '最后登陆时间'
	CreatedAt     time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
