// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDoc = "doc"

// Doc mapped from table <doc>
type Doc struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`      // id
	UserID    int64          `gorm:"column:user_id;not null" json:"user_id"`                 // 用户id
	Title     string         `gorm:"column:title;not null" json:"title"`                     // 标题
	Content   string         `gorm:"column:content;not null" json:"content"`                 // 文档内容
	DocStatus int32          `gorm:"column:doc_status;not null;default:1" json:"doc_status"` // 1正常2审核中3禁用
	GroupID   int32          `gorm:"column:group_id;not null" json:"group_id"`               // 分组id
	ViewCount int32          `gorm:"column:view_count;not null" json:"view_count"`           // 查看次数
	LikeCount int32          `gorm:"column:like_count;not null" json:"like_count"`           // 点赞次数
	IsTop     int32          `gorm:"column:is_top;not null;default:2" json:"is_top"`         // 1置顶2不置顶
	Priority  int32          `gorm:"column:priority;not null" json:"priority"`               // 优先级
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
}

// TableName Doc's table name
func (*Doc) TableName() string {
	return TableNameDoc
}
