// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDocGroup = "doc_group"

// DocGroup mapped from table <doc_group>
type DocGroup struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64          `gorm:"column:user_id;not null" json:"user_id"`   // 用户Id
	Title     string         `gorm:"column:title;not null" json:"title"`       // 组名
	Icon      string         `gorm:"column:icon;not null" json:"icon"`         // 图标
	PID       int64          `gorm:"column:p_id;not null" json:"p_id"`         // 父级id
	Priority  int32          `gorm:"column:priority;not null" json:"priority"` // 优先级
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

// TableName DocGroup's table name
func (*DocGroup) TableName() string {
	return TableNameDocGroup
}
