// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGoodsSpec = "goods_spec"

// GoodsSpec mapped from table <goods_spec>
type GoodsSpec struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GoodID    int32          `gorm:"column:good_id;not null" json:"good_id"`
	Spec      string         `gorm:"column:spec;not null" json:"spec"`         // 规格
	Units     string         `gorm:"column:units" json:"units"`                // 单位
	SpecVal   string         `gorm:"column:spec_val;not null" json:"spec_val"` // 规格值
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName GoodsSpec's table name
func (*GoodsSpec) TableName() string {
	return TableNameGoodsSpec
}
